### ISSUE TITLE
Maybe

### ISSUE THREAD

**Issue by Prohibitive** [izneo-get/readly-get#1]
Hello, thank you very much for this excellent project.
https://go.readly.com/magazines/6267bb4c18250c0007e65cdf
Is there a command to download all issues of the above magazine?
Or can you make such a development?
Thank you so much.
@izneo-get

**Comment by izneo-get** [comment]
I've made an update :  [55fdf7f](https://github.com/izneo-get/readly-get/commit/55fdf7fe8de8dfc63b97e79cee2b7a58bf927506)
Now, instead of downloading only the latest issue of a serie, it can download more issues.

Try:
`python readly_get.py https://go.readly.com/magazines/6267bb4c18250c0007e65cdf --max-dl 10`
and it should download the 10 latest issues in this serie.
